#!/usr/bin/env bash
# Generate a complete Kubernetes manifest for one decoupled agent:
# Deployment + Service + PodDisruptionBudget + HorizontalPodAutoscaler +
# NetworkPolicy (ingress restricted to the backend).
#
# Usage:
#   scripts/gen-agent-k8s.sh <agent-dir-name> > k8s/agents/genie-<name>.yaml
#
# <agent-dir-name> is the agents/cmd/<name> directory (e.g. profile-analyzer,
# aa_fetcher). Underscores become hyphens in K8s resource names (DNS-1123).
#
# Every agent pod carries label genie-agent: "true" so the genie-api egress
# NetworkPolicy (k8s/staging/deployment.yaml) permits backend->agent traffic.
#
# Special agents need extra env appended to the Deployment after generation:
#   portfolio_advisor -> GENIE_DB_DSN (Postgres)
#   educator          -> GENIE_OLLAMA_URL / GENIE_OLLAMA_EMBED (for RAG)
set -euo pipefail

dir="${1:?usage: gen-agent-k8s.sh <agent-dir-name>}"
name="genie-$(echo "$dir" | tr '_' '-')"   # DNS-1123 resource name
image="genie/${dir}:latest"

cat <<YAML
# Generated by scripts/gen-agent-k8s.sh ${dir} — do not edit by hand; regenerate.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${name}
  namespace: genie-staging
  labels:
    app: ${name}
    genie-agent: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${name}
  template:
    metadata:
      labels:
        app: ${name}
        genie-agent: "true"
    spec:
      terminationGracePeriodSeconds: 35   # > the 30s in-process drain budget
      containers:
        - name: ${name}
          image: ${image}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: GENIE_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: genie-agent-secret
                  key: token
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ${name}
  namespace: genie-staging
spec:
  selector:
    app: ${name}
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ${name}-pdb
  namespace: genie-staging
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ${name}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${name}-hpa
  namespace: genie-staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${name}
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ${name}-netpol
  namespace: genie-staging
spec:
  podSelector:
    matchLabels:
      app: ${name}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: genie-api   # only the backend may call this agent
      ports:
        - protocol: TCP
          port: 8080
YAML
